publishDir = "../"
baseURL = 'https://jpacheco.xyz'
languageCode = "en-us"
title = "jpacheco.xyz"
theme = "cactus"
copyright = "Javier Pacheco" # cactus will use title if copyright is not set

summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4
#
[[menu.main]]
name = "Search"
url = "/search"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "doom-one2" # https://xyproto.github.io/splash/docs/all.html
    tabWidth = 4

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  opengraph_io_api_key = "KGV7XE9-05EMV9G-JM7YAYE-ZJGANWM"

  # Home page settings
  description = "Hello! I’m Javier Pacheco, an enthusiast in automation and programming. I love innovating and automating processes to make life easier. I am passionate about Linux because it's Open Source, highly customizable & encourages freedom and knowledge sharing. If you have any questions or would like to get in touch, send me an email."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/jpachecoxyz" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  # [params.comments]
  #   enabled = true # default
  #   engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
  #   [params.comments.utterances]
  #     repo = "<github_username>/<github_reponame>"
  #     label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
  #     theme = "github-light"
  #   [params.comments.cactuscomments]
  #     siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
  #     #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
  #     #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  css = ["css/style.css"]

  [[params.social]]
    name = "github"
    link = "https://github.com/jpachecoxyz"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/jpachecom4"
  [[params.social]]
    name = "email"
    link = "javier@jpacheco.xyz"  # no need for "mailto:" in the head

[outputs]
  home = ["HTML", "RSS", "JSON"]
