baseurl      = "/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My personal blog."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  archetypeDir = "archetypes"
  contentDir   = "content"
  dataDir      = "data"
  layoutDir    = "layouts"
  publishDir   = "docs"

  buildDrafts  = false
  buildFuture  = false
  buildExpired = false
  canonifyURLs = true

  enableRobotsTXT = true
  enableGitInfo   = false
  enableEmoji     = true
  enableMissingTranslationPlaceholders = false
  disableRSS     = false
  disableSitemap = false
  disable404     = false
  disableHugoGeneratorInject = false
  enableThemeToggle = false

  [params.author]
    name = "Javier Pacheco"

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    # trademark = 2023
    rss = true
    copyright = false
    author = true

    topText = []

[services]
  [services.rss]
      # Maximum number of items in the RSS feed.
      limit = 42
      
#   [services.disqus]
#     shortname = 'your-disqus-shortname'
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/"

[[params.social]]
  name = "email"
  url  = "mailto:nobody@example.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/"

[[params.social]]
  name = "stackoverflow"
  url  = "https://www.stackoverflow.com/"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "jpachecoxyz's Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "jpachecoxyz"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
