* [[file:index.org][(2025-01-06) Javier Pacheco]]
(No preview)
* [[file:archive.org][(2025-01-06) Posts Archive]]
(No preview)
* [[file:about.org][(2025-01-06) About Me]]
(No preview)
* posts
** [[file:posts/emacs-vs-nvim.org][(2025-01-07) Emacs vs Neovim]]
My thoughts about these fantastics text editors.
** [[file:posts/a-job-history.org][(2024-12-26) A job history.]]
(No preview)
** [[file:posts/ollama.org][(2024-09-22) Ellama, a emacs AI helper.]]
(No preview)
** [[file:posts/wiki.org][(2024-09-03) Wiki]]
This is my wiki about some tips and important notes.
** [[file:posts/voidstrap-a-tui-void-linux-installator.org][(2024-01-01) Voidstrap a tui void linux installator]]
This is the first post of the 2024, this is a project that I am working on in the last
year, is a minimialist voidlinux instalator it is based in some recomendations in 
a guides that some friends of my have but "semiautomated".
** [[file:posts/copy-org-blocks-to-clipboard.org][(2023-12-29) Copy org blocks to clipboard]]
In this post I'll demostrate how to add a button to copy the content of a 
src block generated by ox-publish in emacs within org-mode, this script
create a button in every instance of codeblock in the html file that ox-publish
generate when create the web-page content.
** [[file:posts/attempt-to-test-rss-feeds.org][(2023-12-26) Attempt to test RSS feeds]]
Hello.

This post, is about  more like a testing, because, I'm trying to add RSS feeds into 
this "web-page", so basically this is a test, and see if when I build the webpage
is going to work... or not.
So, this is the preview and read this post to see what I'm trying to do.
** [[file:posts/denote-silo-function.org][(2023-12-25) Denote silo function]]
I have been reading some thing information about denote, and its powerful tools
that the good =prots= give to us the mortals. I am starting this "post" thing, and 
is good to have my notes apart from the posts that I'm going to write in the 
future, so reading I find a interesting function that prots suggest to use 
in the creation of notes.
** [[file:posts/themes-and-end-of-the-year.org][(2023-12-23) Themes and end of the year]]
This is the first of a few posts I'm creating this "web" only for my knowledge,
and contribute with some of it.

Some things are happening by a reason, so, instead of see the "bad" things that
happens; is a better practice to see the good side of the thing, these more or less
are some phrases that my dad says to me when me and my family have some problems.