baseURL: https://mivinci.github.io/hugo-theme-minima

languageCode: en-us

title: Hugo on Minima

copyright: © 2020-2024 Leo X

googleAnalytics:

pagination:
  pagerSize: 4
  # Specify the number of posts listed at home page

theme: hugo-theme-minima
# Specify a theme to use

defaultContentLanguage: en
# Specify the default language

languages:
# Override language-specific configurations
  en:
    languageName: EN
    weight: 1
    
  zh-cn:
    languageName: 简中
    weight: 2
    params:
      greet: 你好 :)
      author:
        status: 目前住在地球 🌍
        description: |
          这是 Minima, 一个简洁的 Hugo 主题，移植自 [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima)。
          支持深色模式、多语言、数学公式、流程图、代码语法高亮，当然还有分类、标签、系列等等。

params:
# Define regular configurations

  greet: Hello :)
  
  subtitle:
  
  switch: ["🌚", "🌝"]
  
  defaultTheme: system
  # Specify the default color theme, available values: light, sand, rock, system.

  displayDate: true

  displayDescription: true

  selectable: true

  author:
    name: Leo X
    status: Currently living on Earth 🌍
    avatar: https://avatars.githubusercontent.com/u/33592375?v=4
    description: |
      This is Minima, a clean and minimal Hugo theme porting from 
      [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima). It has supports 
      for dark mode, multilingual mode, math formulas, flowcharts, syntax highlighting, 
      and of course taxonomies like categories, tags, and series.

  social:
    - name: "twitter"
      url: "https://twitter.com/realmivinci"
    - name: "email"
      url: "mailto:mivinci@qq.com"
    - name: "github"
      url: "https://github.com/mivinci/hugo-theme-minima"
    - name: "rss"
      url: "index.xml"

  math:
    enable: true
    provider: katex

  diagram:
    enable: true
    provider: mermaid

  comment:
    enable: true
    provider: giscus

    disqus:
    # See also https://disqus.com
      shortname: hugo-minima

    utterances:
    # See also https://utteranc.es
      repo: mivinci/hugo-theme-minima
      issueTerm: pathname
      label: comment

    giscus: 
    # See also https://giscus.app
      repo: mivinci/hugo-theme-minima
      repoId: MDEwOlJlcG9zaXRvcnkzODcxMjM2NDU=
      category: Comments
      categoryId: DIC_kwDOFxMJvc4CScQm
      mapping: pathname
      inputPosition: buttom # bottom | top
      reactions: true
      metadata: false

  search:
    enable: true
    provider: fuse
    title: Search
    placeholder: Enter keywords

    fuse:
    # See also https://fusejs.io
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: false
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: false

menu:
  main:
    - identifier: home
      name: Home
      weight: 1
    - identifier: tags
      name: Tags
      weight: 2
    - identifier: series
      name: Series
      weight: 3
    - identifier: search
      name: 🔍
      weight: 4

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
# **DO NOT EDIT** anything below. 
# Because unlike other Hugo themes, the way Minima uses to do syntax
# highlighting depends strongly on configurations below, so that the
# color theme of code blocks changes with the blog color theme, instead
# of being static like you may have seen on other Hugo themes.
  highlight:
    lineNos: true
    noClasses: false
